id: IC91CCBDF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T11:04:54+00:00'
last_modified: '2022-06-08T05:45:38.656670+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21295
  title: རྒྱུད་སྡེ་ཀུན་བཏུས། （སྡེ་དགེ་པར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    EE58:
      image_group_id: I2432
      title: ''
      total_pages: 608
      order: 1
      base_file: EE58.txt
    '5444':
      image_group_id: I2433
      title: ''
      total_pages: 668
      order: 2
      base_file: 5444.txt
    5E54:
      image_group_id: I2434
      title: ''
      total_pages: 566
      order: 3
      base_file: 5E54.txt
    DEEA:
      image_group_id: I2435
      title: ''
      total_pages: 548
      order: 4
      base_file: DEEA.txt
    AADF:
      image_group_id: I2436
      title: ''
      total_pages: 732
      order: 5
      base_file: AADF.txt
    D1A0:
      image_group_id: I2437
      title: ''
      total_pages: 722
      order: 6
      base_file: D1A0.txt
    A3DD:
      image_group_id: I2438
      title: ''
      total_pages: 816
      order: 7
      base_file: A3DD.txt
    BE5F:
      image_group_id: I2439
      title: ''
      total_pages: 738
      order: 8
      base_file: BE5F.txt
    BAB9:
      image_group_id: I2440
      title: ''
      total_pages: 664
      order: 9
      base_file: BAB9.txt
    E33B:
      image_group_id: I2441
      title: ''
      total_pages: 756
      order: 10
      base_file: E33B.txt
    C061:
      image_group_id: I2442
      title: ''
      total_pages: 693
      order: 11
      base_file: C061.txt
    '4270':
      image_group_id: I2443
      title: ''
      total_pages: 566
      order: 12
      base_file: 4270.txt
    E981:
      image_group_id: I2444
      title: ''
      total_pages: 626
      order: 13
      base_file: E981.txt
    21F1:
      image_group_id: I2445
      title: ''
      total_pages: 630
      order: 14
      base_file: 21F1.txt
    '3876':
      image_group_id: I2446
      title: ''
      total_pages: 636
      order: 15
      base_file: 3876.txt
    47B8:
      image_group_id: I2447
      title: ''
      total_pages: 686
      order: 16
      base_file: 47B8.txt
    DD1D:
      image_group_id: I2448
      title: ''
      total_pages: 726
      order: 17
      base_file: DD1D.txt
    '2620':
      image_group_id: I2449
      title: ''
      total_pages: 626
      order: 18
      base_file: 2620.txt
    596A:
      image_group_id: I2450
      title: ''
      total_pages: 636
      order: 19
      base_file: 596A.txt
    F494:
      image_group_id: I2451
      title: ''
      total_pages: 784
      order: 20
      base_file: F494.txt
    '2037':
      image_group_id: I2452
      title: ''
      total_pages: 772
      order: 21
      base_file: 2037.txt
    0B0B:
      image_group_id: I2453
      title: ''
      total_pages: 680
      order: 22
      base_file: 0B0B.txt
    '2548':
      image_group_id: I2454
      title: ''
      total_pages: 674
      order: 23
      base_file: 2548.txt
    345A:
      image_group_id: I2455
      title: ''
      total_pages: 610
      order: 24
      base_file: 345A.txt
    ABD4:
      image_group_id: I2456
      title: ''
      total_pages: 606
      order: 25
      base_file: ABD4.txt
    EDDD:
      image_group_id: I2457
      title: ''
      total_pages: 640
      order: 26
      base_file: EDDD.txt
    090B:
      image_group_id: I2458
      title: ''
      total_pages: 654
      order: 27
      base_file: 090B.txt
    '1761':
      image_group_id: I2459
      title: ''
      total_pages: 636
      order: 28
      base_file: 1761.txt
    26FC:
      image_group_id: I2460
      title: ''
      total_pages: 628
      order: 29
      base_file: 26FC.txt
    C6CC:
      image_group_id: I2461
      title: ''
      total_pages: 646
      order: 30
      base_file: C6CC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
