id: IC91CCBDF
legacy_id: P006632
ocr_import_info:
  bdrc_scan_id: W21295
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T10:58:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T14:00:15.541414+00:00'
last_modified: 2022-09-01 22:09:59.666196
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W21295
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW21295
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱུད་སྡེ་ཀུན་བཏུས། （སྡེ་དགེ་པར་མ།）
statistics:
  ocr_word_mean_confidence_index: 0.5633462792769636
  ocr_word_median_confidence_index: 0.5699999928474426
quality: null
bases:
  I2453:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2453
      total_pages: 680
      volume_number: 22
      volume_pages_bdrc_intro: 2
    order: 22
    base_file: I2453.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.602579585590015
    legacy_id: v022
  I2455:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2455
      total_pages: 610
      volume_number: 24
      volume_pages_bdrc_intro: 2
    order: 24
    base_file: I2455.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5474147321616982
    legacy_id: v024
  I2444:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2444
      total_pages: 626
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I2444.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5248819360782937
    legacy_id: v013
  I2432:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2432
      total_pages: 608
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2432.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5585713262405666
    legacy_id: v001
  I2433:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2433
      total_pages: 668
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2433.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5696209545308638
    legacy_id: v002
  I2446:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2446
      total_pages: 636
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I2446.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5668646138905139
    legacy_id: v015
  I2442:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2442
      total_pages: 693
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I2442.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5820030620288753
    legacy_id: v011
  I2452:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2452
      total_pages: 772
      volume_number: 21
      volume_pages_bdrc_intro: 2
    order: 21
    base_file: I2452.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5467906232488816
    legacy_id: v021
  I2437:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2437
      total_pages: 722
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2437.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5782127076121844
    legacy_id: v006
  I2460:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2460
      total_pages: 628
      volume_number: 29
      volume_pages_bdrc_intro: 2
    order: 29
    base_file: I2460.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5577599605858865
    legacy_id: v029
  I2436:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2436
      total_pages: 732
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2436.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5442575027559414
    legacy_id: v005
  I2449:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2449
      total_pages: 626
      volume_number: 18
      volume_pages_bdrc_intro: 2
    order: 18
    base_file: I2449.txt
    statistics:
      ocr_word_median_confidence_index: 0.5199999809265137
      ocr_word_mean_confidence_index: 0.5332656618820081
    legacy_id: v018
  I2457:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2457
      total_pages: 640
      volume_number: 26
      volume_pages_bdrc_intro: 2
    order: 26
    base_file: I2457.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5841225097676535
    legacy_id: v026
  I2440:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2440
      total_pages: 664
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I2440.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5477720747181125
    legacy_id: v009
  I2454:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2454
      total_pages: 674
      volume_number: 23
      volume_pages_bdrc_intro: 2
    order: 23
    base_file: I2454.txt
    statistics:
      ocr_word_median_confidence_index: 0.5299999713897705
      ocr_word_mean_confidence_index: 0.544447987524116
    legacy_id: v023
  I2443:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2443
      total_pages: 566
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I2443.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5241384139551478
    legacy_id: v012
  I2447:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2447
      total_pages: 686
      volume_number: 16
      volume_pages_bdrc_intro: 2
    order: 16
    base_file: I2447.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5238234292411517
    legacy_id: v016
  I2434:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2434
      total_pages: 566
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2434.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6118288615146976
    legacy_id: v003
  I2441:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2441
      total_pages: 756
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I2441.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5431757489721257
    legacy_id: v010
  I2435:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2435
      total_pages: 548
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2435.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5672789071306504
    legacy_id: v004
  I2461:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2461
      total_pages: 646
      volume_number: 30
      volume_pages_bdrc_intro: 2
    order: 30
    base_file: I2461.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6155502747452819
    legacy_id: v030
  I2456:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2456
      total_pages: 606
      volume_number: 25
      volume_pages_bdrc_intro: 2
    order: 25
    base_file: I2456.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5282706095957537
    legacy_id: v025
  I2439:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2439
      total_pages: 738
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I2439.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5668618776160929
    legacy_id: v008
  I2458:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2458
      total_pages: 654
      volume_number: 27
      volume_pages_bdrc_intro: 2
    order: 27
    base_file: I2458.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5829020250308904
    legacy_id: v027
  I2438:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2438
      total_pages: 816
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I2438.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.6021114571722692
    legacy_id: v007
  I2451:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2451
      total_pages: 784
      volume_number: 20
      volume_pages_bdrc_intro: 2
    order: 20
    base_file: I2451.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6441154256083699
    legacy_id: v020
  I2459:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2459
      total_pages: 636
      volume_number: 28
      volume_pages_bdrc_intro: 2
    order: 28
    base_file: I2459.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5683493745446315
    legacy_id: v028
  I2445:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2445
      total_pages: 630
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I2445.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5489335820341862
    legacy_id: v014
  I2450:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2450
      total_pages: 636
      volume_number: 19
      volume_pages_bdrc_intro: 2
    order: 19
    base_file: I2450.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5521362150150205
    legacy_id: v019
  I2448:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2448
      total_pages: 726
      volume_number: 17
      volume_pages_bdrc_intro: 2
    order: 17
    base_file: I2448.txt
    statistics:
      ocr_word_median_confidence_index: 0.5299999713897705
      ocr_word_mean_confidence_index: 0.5372618878504376
    legacy_id: v017
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
